const store = {
    ingredients: [],
    currentIngredients: [],
    ingredient: {},
    order: {},
    ingredientsRequest: false,
    ingredientsSuccess: false,
    ingredientsFailed: false,
    totalPrice: 0,
    bun: {},
    isBunAdded: false,
    sendOrderRequest: false,
    sendOrderSuccess: false,
    sendOrderFailed: false,
    counterIngredients: [],
    savePasswordRequest: false,
    savePasswordSuccess: false,
    savePasswordFailed: false,
    createUserRequest: false,
    createUserSuccess: false,
    createUserFailed: false,
    loginUserRequest: false,
    loginUserSuccess: false,
    loginUserFailed: false,
    user: {},
    isAuthenticated: false,
    errorMessage: '',
    getUserRequest: false,
    getUserSuccess: false,
    getUserFailed: false,
    updateUserSuccess: false,
    refreshTokenRequest: false,
    refreshTokenSuccess: false,
    refreshTokenFailed: false,
    logoutSuccess: false

};

export default store;

