export const SAVE_PASSWORD_REQUEST: 'SAVE_PASSWORD_REQUEST' = "SAVE_PASSWORD_REQUEST";
export const SAVE_PASSWORD_SUCCESS: 'SAVE_PASSWORD_SUCCESS' = "SAVE_PASSWORD_SUCCESS";
export const SAVE_PASSWORD_ERROR: 'SAVE_PASSWORD_ERROR' = "SAVE_PASSWORD_ERROR";

export const CREATE_USER_REQUEST: 'CREATE_USER_REQUEST' = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS' = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR: 'CREATE_USER_ERROR' = "CREATE_USER_ERROR";

export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS' = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR: 'LOGIN_USER_ERROR' = "LOGIN_USER_ERROR";

export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = "GET_USER_SUCCESS";
export const GET_USER_REQUEST: 'GET_USER_REQUEST' = "GET_USER_REQUEST";
export const GET_USER_ERROR: 'GET_USER_ERROR' = "GET_USER_ERROR";

export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR: 'UPDATE_USER_ERROR' = 'UPDATE_USER_ERROR';

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR' = "REFRESH_TOKEN_ERROR";

export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = "LOGOUT_SUCCESS";